#server
server:
  port: 8080
#mybatis_config  
mybatis:  
    #mapper-locations: classpath:com/lzz/potato/dao/*.xml
    config-location: classpath:mybatis-config.xml
spring:  
    #thymeleaf start
    thymeleaf:
      mode: HTML5
      servlet:
        content-type: text/html
      encoding: UTF-8
      cache: false
    #thymeleaf end
    #datasource
    datasource:  
        name: datasource
        url: jdbc:mysql://localhost:3306/db_potato?useUnicode=true&characterEncoding=UTF-8
        username: root  
        password: a
        # 使用druid数据源  
        type: com.alibaba.druid.pool.DruidDataSource  
        driver-class-name: com.mysql.jdbc.Driver
        # 下面为连接池的补充设置，应用到上面所有数据源中  
        # 初始化大小，最小，最大  
        initialSize: 5
        minIdle: 5  
        maxActive: 20  
        # 配置获取连接等待超时的时间  
        maxWait: 60000  
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒  
        timeBetweenEvictionRunsMillis: 60000  
        # 配置一个连接在池中最小生存的时间，单位是毫秒  
        minEvictableIdleTimeMillis: 300000  
        #用来验证数据库连接的有效性
        #Oracle select 1 from dual
        #mysql select 1
        validationQuery: SELECT 1  
        #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        testWhileIdle: true  
        # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnBorrow: false  
        #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testOnReturn: false  
        # 打开PSCache，并且指定每个连接上PSCache的大小 ,PSCache对支持游标的数据库性能提升巨大
        poolPreparedStatements: false 
        # 指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize: 20
         # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，stat用于统计,'wall'用于防火墙
        filters: stat, wall
        # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true